# This file was generated by the {rix} R package v0.18.2 on 2026-07-08
# with following call:
# >rix(date = "2026-06-22",
#  > r_pkgs = required_packages,
#  > system_pkgs = c("quarto",
#  > "git",
#  > "pandoc",
#  > "typst",
#  > "stanc",
#  > "tbb",
#  > "gettext",
#  > "libintl"),
#  > git_pkgs = list(list(package_name = "cmdstanr",
#  > repo_url = "https://github.com/stan-dev/cmdstanr",
#  > commit = "541f36c74c236a322eaa0908e2e86425790ca2cf"),
#  > list(package_name = "brms.exgaussian",
#  > repo_url = "https://github.com/mattansb/brms.exgaussian",
#  > commit = "53b0745e10147b902acb4e40d72e0dd64033c311")),
#  > tex_pkgs = c("amsmath",
#  > "ninecolors",
#  > "apa7",
#  > "scalerel",
#  >      "threeparttable",
#  > "threeparttablex",
#  > "endfloat",
#  > "environ",
#  > "multirow",
#  > "tcolorbox",
#  > "pdfcol",
#  > "tikzfill",
#  > "fontawesome5",
#  > "framed",
#  > "newtx",
#  > "fontaxes",
#  > "xstring",
#  > "wrapfig",
#  > "tabularray",
#  > "siunitx",
#  > "fvextra",
#  > "geometry",
#  > "setspace",
#  > "fancyvrb",
#  > "anyfontsize"),
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = "Rscript install_cmdstan.R",
#  > r_ver = "4.6.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-06-22.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      brms
      collapse
      easystats
      ggdist
      ggplot2
      knitr
      marginaleffects
      ragg
      reformulas
      rmarkdown
      tinytable;
  };
 
    brms.exgaussian = (pkgs.rPackages.buildRPackage {
      name = "brms.exgaussian";
      src = pkgs.fetchgit {
        url = "https://github.com/mattansb/brms.exgaussian";
        rev = "53b0745e10147b902acb4e40d72e0dd64033c311";
        sha256 = "sha256-dnZ48VaYC3RpT5RbfG826bxMMf+VnUKNj3kdutSTll0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          brms;
      };
    });

    cmdstanr = (pkgs.rPackages.buildRPackage {
      name = "cmdstanr";
      src = pkgs.fetchgit {
        url = "https://github.com/stan-dev/cmdstanr";
        rev = "541f36c74c236a322eaa0908e2e86425790ca2cf";
        sha256 = "sha256-4qf52WZ50S0PdeKVKe08jvWCegbf9H+QZCyoq7w2Xy4=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          checkmate
          data_table
          jsonlite
          posterior
          processx
          R6
          withr
          rlang;
      };
    });
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      anyfontsize
      apa7
      endfloat
      environ
      fancyvrb
      fontawesome5
      fontaxes
      framed
      fvextra
      geometry
      multirow
      newtx
      ninecolors
      pdfcol
      scalerel
      setspace
      siunitx
      tabularray
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      wrapfig
      xstring;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      gettext
      git
      glibcLocales
      libintl
      nix
      pandoc
      positron-bin
      quarto
      R
      stanc
      tbb
      typst
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ cmdstanr brms.exgaussian rpkgs tex system_packages ];
    shellHook = ''
    Rscript install_cmdstan.R
  '';
  }; 
in
  {
    inherit pkgs shell;
  }
